spring.application.name=reference

#Docker
#spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/postgres
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
# Database URL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres

# Credentials
spring.datasource.username=postgres
spring.datasource.password=postgres

# Driver (optional in Spring Boot 3)
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialect (optional in Boot 3+)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#server port
#server.port=9999

# Enable all actuator endpoints
management.endpoints.web.exposure.include=*

# Show health details
management.endpoint.health.show-details=always

# (Optional) Change actuator base path
management.endpoints.web.base-path=/actuator
